---
- hosts: loadbalancer
  become: true
  tasks:
    - name: verify nginx service
      command: service nginx status

    - name: verify nginx is listening on 80
      wait_for: port=80 timeout=1

- hosts: webserver
  become: true
  tasks:
    - name: verify apache2 service
      command: service apache2 status

    - name: verify apache2 is listening on 80
      wait_for: port=80 timeout=1

- hosts: database
  become: true
  tasks:
    - name: verify mysql service
      command: service mysql status

    - name: verify mysql is listening on 3306
      wait_for: port=3306 timeout=1

- hosts: controller
  tasks:
    - name: verify end-to-end index response
      uri: url=http://lb01 return_content=yes
      register: lb_index
      failed_when: "'Hello, from sunny' not in lb_index.content"

    - name: verify end-to-end db response
      uri: url=http://lb01/db return_content=yes
      register: lb_db
      failed_when: "'Database Connected from' not in lb_db.content"

- hosts: loadbalancer
  tasks:
    - name: verify end-to-end index response
      uri: url=http://app01 return_content=yes
      register: app_index
      failed_when: "'Hello, from sunny' not in app_index.content"
      
    - name: verify end-to-end index response
      uri: url=http://app02 return_content=yes
      register: app_index
      failed_when: "'Hello, from sunny' not in app_index.content"

    - name: verify end-to-end db response
      uri: url=http://app01/db return_content=yes
      register: app_db
      failed_when: "'Database Connected from' not in app_db.content"
      
    - name: verify end-to-end db response
      uri: url=http://app02/db return_content=yes
      register: app_db
      failed_when: "'Database Connected from' not in app_db.content"
